### ISSUE TITLE
after issue "vagrant up"  procedure does not progress

### ISSUE THREAD

**Issue by sk3pp3r** [ops-school/candidates-assignment#2]
after issue command "vagrant up"
I`m got this output lines:
Bringing machine 'server1' up with 'virtualbox' provider...
Bringing machine 'server2' up with 'virtualbox' provider...
==> server1: Importing base box 'hashicorp/precise64'...
==> server1: Matching MAC address for NAT networking...
==> server1: Checking if box 'hashicorp/precise64' is up to date...
==> server1: Setting the name of the VM: vagrant_server1_1534754999444_88533
==> server1: Clearing any previously set network interfaces...
==> server1: Preparing network interfaces based on configuration...
    server1: Adapter 1: nat
    server1: Adapter 2: hostonly
==> server1: Forwarding ports...
    server1: 22 (guest) => 2222 (host) (adapter 1)
==> server1: Running 'pre-boot' VM customizations...
==> server1: Booting VM...
==> server1: Waiting for machine to boot. This may take a few minutes...
    server1: SSH address: 127.0.0.1:2222
    server1: SSH username: vagrant
    server1: SSH auth method: private key
    server1:
    server1: Vagrant insecure key detected. Vagrant will automatically replace
    server1: this with a newly generated keypair for better security.
    server1:
    server1: Inserting generated public key within guest...
    server1: Removing insecure key from the guest if it's present...
    server1: Key inserted! Disconnecting and reconnecting using new SSH key...
==> server1: Machine booted and ready!
==> server1: Checking for guest additions in VM...
    server1: The guest additions on this VM do not match the installed version of
    server1: VirtualBox! In most cases this is fine, but in rare cases it can
    server1: prevent things such as shared folders from working properly. If you see
    server1: shared folder errors, please make sure the guest additions within the
    server1: virtual machine match the version of VirtualBox you have installed on
    server1: your host and reload your VM.
    server1:
    server1: Guest Additions Version: 4.2.0
    server1: VirtualBox Version: 5.2
==> server1: Setting hostname...

and the procedure does not progress

OS Ver: Microsoft Windows [Version 6.1.7601]
VirtualBox ver: 5.2.18
Vagrant Ver: 2.1.2
Commands run under admin rights

**Comment by gairadzi** [comment]
Hi @sk3pp3r,
I was able to recreate it and I think it's an issue with that specific vagrant box.
I updated the repository and changed the box used in the exercise.
Please check if it solves the issue for you.

Thanks,

**Comment by alexg84** [comment]
i removed the line "node.vm.hostname = machine[:hostname]" from the Vagrantfile and its solves the issue

**Comment by sk3pp3r** [comment]
also in my case, remark line  "node.vm.hostname = machine[:hostname]" from the Vagrantfile fix this.
