### ISSUE TITLE
Can't find the vagrant directory after I clone the repo locally

### ISSUE THREAD

**Issue by Michabitton** [ops-school/candidates-assignment#3]
Steps:
Clone locally the repo:
https://github.com/ops-school/candidates-assignment.git

Mirror to my new Repo
https://github.com/MichaBitton/OpsSchool.git

remove the old repo candidates-assignment.git

cd OpsSchool.git
Didn't find the vagrant folder.

**Comment by boulidad** [comment]
I'm not sure what the issue  on your laptop, your repo looks fine
I suggest that you delete your local directory and clone your repo arain.
